[workspace]
members = ["kernel", "user_lib", "user_apps"]
default-members = ["kernel"]
resolver = "2"

[workspace.dependencies]
log = "0.4"
riscv = "0.11.1"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.9.8"
